apiVersion: v1
kind: Service

metadata:
  name: zookeeper-headless
  labels:
    app: zookeeper

spec:
  clusterIP: None
  selector:
    app: zookeeper
  ports:
  - port: 2181
    name: client
  - port: 3888
    name: election
  - port: 2888
    name: server

---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: zookeeper

spec:
  selector:
    matchLabels:
      app: zookeeper
  serviceName: "zookeeper-headless"
  replicas: 3
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: zookeeper
        image: zookeeper:3.5

        ports:
        - containerPort: 2181
          name: client
        - containerPort: 3888
          name: election
        - containerPort: 2888
          name: server

        volumeMounts:
        - name: data
          mountPath: /var/lib/zookeeper

        command:
        - bash
        - "-c"
        - |
          set -ex
          [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
          ordinal=$((${BASH_REMATCH[1]} + 1))
          ZOO_MY_ID=${ordinal}
          ZOO_SERVERS="quorumListenOnAllIPs=true zookeeper-0.zookeeper:2888:3888,zookeeper-1.zookeeper:2888:3888,zookeeper-2.zookeeper:2888:3888"
          /docker-entrypoint.sh zkServer.sh start-foreground

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 1Gi
